package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Axy kernel
var Axy_code cu.Function

// Stores the arguments for Axy kernel invocation
type Axy_args_t struct{
	 arg_s unsafe.Pointer
	 arg_phiDot unsafe.Pointer
	 arg_rxyAvg unsafe.Pointer
	 arg_dwpos unsafe.Pointer
	 arg_mw int
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 argptr [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Axy kernel invocation
var Axy_args Axy_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Axy_args.argptr[0] = unsafe.Pointer(&Axy_args.arg_s)
	 Axy_args.argptr[1] = unsafe.Pointer(&Axy_args.arg_phiDot)
	 Axy_args.argptr[2] = unsafe.Pointer(&Axy_args.arg_rxyAvg)
	 Axy_args.argptr[3] = unsafe.Pointer(&Axy_args.arg_dwpos)
	 Axy_args.argptr[4] = unsafe.Pointer(&Axy_args.arg_mw)
	 Axy_args.argptr[5] = unsafe.Pointer(&Axy_args.arg_Nx)
	 Axy_args.argptr[6] = unsafe.Pointer(&Axy_args.arg_Ny)
	 Axy_args.argptr[7] = unsafe.Pointer(&Axy_args.arg_Nz)
	 }

// Wrapper for Axy CUDA kernel, asynchronous.
func k_Axy_async ( s unsafe.Pointer, phiDot unsafe.Pointer, rxyAvg unsafe.Pointer, dwpos unsafe.Pointer, mw int, Nx int, Ny int, Nz int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Axy")
	}

	Axy_args.Lock()
	defer Axy_args.Unlock()

	if Axy_code == 0{
		Axy_code = fatbinLoad(Axy_map, "Axy")
	}

	 Axy_args.arg_s = s
	 Axy_args.arg_phiDot = phiDot
	 Axy_args.arg_rxyAvg = rxyAvg
	 Axy_args.arg_dwpos = dwpos
	 Axy_args.arg_mw = mw
	 Axy_args.arg_Nx = Nx
	 Axy_args.arg_Ny = Ny
	 Axy_args.arg_Nz = Nz
	

	args := Axy_args.argptr[:]
	cu.LaunchKernel(Axy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Axy")
	}
}

// maps compute capability on PTX code for Axy kernel.
var Axy_map = map[int]string{ 0: "" ,
30: Axy_ptx_30 ,
35: Axy_ptx_35 ,
37: Axy_ptx_37 ,
50: Axy_ptx_50 ,
52: Axy_ptx_52 ,
53: Axy_ptx_53 ,
60: Axy_ptx_60 ,
61: Axy_ptx_61 ,
70: Axy_ptx_70 ,
75: Axy_ptx_75  }

// Axy PTX code for various compute capabilities.
const(
  Axy_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.f32 	%f7, [%rd13];
	ld.global.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
   Axy_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	Axy

.visible .entry Axy(
	.param .u64 Axy_param_0,
	.param .u64 Axy_param_1,
	.param .u64 Axy_param_2,
	.param .u64 Axy_param_3,
	.param .u32 Axy_param_4,
	.param .u32 Axy_param_5,
	.param .u32 Axy_param_6,
	.param .u32 Axy_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [Axy_param_0];
	ld.param.u64 	%rd2, [Axy_param_1];
	ld.param.u64 	%rd3, [Axy_param_2];
	ld.param.u64 	%rd4, [Axy_param_3];
	ld.param.u32 	%r5, [Axy_param_4];
	ld.param.u32 	%r6, [Axy_param_5];
	ld.param.u32 	%r7, [Axy_param_6];
	ld.param.u32 	%r8, [Axy_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd6, %r4, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd7];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB0_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB0_4;

	cvta.to.global.u64 	%rd8, %rd1;
	cvta.to.global.u64 	%rd9, %rd3;
	cvta.to.global.u64 	%rd10, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd10, %rd11;
	add.s64 	%rd13, %rd9, %rd11;
	ld.global.nc.f32 	%f7, [%rd13];
	ld.global.nc.f32 	%f8, [%rd12];
	mul.f32 	%f9, %f8, %f7;
	add.s64 	%rd14, %rd8, %rd11;
	st.global.f32 	[%rd14], %f9;

BB0_4:
	ret;
}

	// .globl	Az
.visible .entry Az(
	.param .u64 Az_param_0,
	.param .u64 Az_param_1,
	.param .u64 Az_param_2,
	.param .u64 Az_param_3,
	.param .u32 Az_param_4,
	.param .u32 Az_param_5,
	.param .u32 Az_param_6,
	.param .u32 Az_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [Az_param_0];
	ld.param.u64 	%rd2, [Az_param_1];
	ld.param.u64 	%rd3, [Az_param_3];
	ld.param.u32 	%r5, [Az_param_4];
	ld.param.u32 	%r6, [Az_param_5];
	ld.param.u32 	%r7, [Az_param_6];
	ld.param.u32 	%r8, [Az_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB1_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mad.lo.s32 	%r4, %r3, %r7, %r2;
	mul.wide.s32 	%rd5, %r4, 4;
	add.s64 	%rd6, %rd4, %rd5;
	cvt.rn.f32.s32	%f1, %r5;
	ld.global.nc.f32 	%f2, [%rd6];
	sub.f32 	%f4, %f2, %f1;
	cvt.rn.f32.s32	%f3, %r1;
	setp.lt.f32	%p6, %f3, %f4;
	@%p6 bra 	BB1_4;

	add.f32 	%f5, %f1, %f2;
	add.f32 	%f6, %f5, 0f3F800000;
	setp.gt.f32	%p7, %f3, %f6;
	@%p7 bra 	BB1_4;

	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd2;
	mad.lo.s32 	%r18, %r4, %r6, %r1;
	mul.wide.s32 	%rd9, %r18, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f7, [%rd10];
	add.s64 	%rd11, %rd7, %rd9;
	st.global.f32 	[%rd11], %f7;

BB1_4:
	ret;
}


`
 )
