package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for dwPosInterpolated kernel
var dwPosInterpolated_code cu.Function

// Stores the arguments for dwPosInterpolated kernel invocation
type dwPosInterpolated_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_zc unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 argptr [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for dwPosInterpolated kernel invocation
var dwPosInterpolated_args dwPosInterpolated_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 dwPosInterpolated_args.argptr[0] = unsafe.Pointer(&dwPosInterpolated_args.arg_dst)
	 dwPosInterpolated_args.argptr[1] = unsafe.Pointer(&dwPosInterpolated_args.arg_zc)
	 dwPosInterpolated_args.argptr[2] = unsafe.Pointer(&dwPosInterpolated_args.arg_mz)
	 dwPosInterpolated_args.argptr[3] = unsafe.Pointer(&dwPosInterpolated_args.arg_Nx)
	 dwPosInterpolated_args.argptr[4] = unsafe.Pointer(&dwPosInterpolated_args.arg_Ny)
	 dwPosInterpolated_args.argptr[5] = unsafe.Pointer(&dwPosInterpolated_args.arg_Nz)
	 }

// Wrapper for dwPosInterpolated CUDA kernel, asynchronous.
func k_dwPosInterpolated_async ( dst unsafe.Pointer, zc unsafe.Pointer, mz unsafe.Pointer, Nx int, Ny int, Nz int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("dwPosInterpolated")
	}

	dwPosInterpolated_args.Lock()
	defer dwPosInterpolated_args.Unlock()

	if dwPosInterpolated_code == 0{
		dwPosInterpolated_code = fatbinLoad(dwPosInterpolated_map, "dwPosInterpolated")
	}

	 dwPosInterpolated_args.arg_dst = dst
	 dwPosInterpolated_args.arg_zc = zc
	 dwPosInterpolated_args.arg_mz = mz
	 dwPosInterpolated_args.arg_Nx = Nx
	 dwPosInterpolated_args.arg_Ny = Ny
	 dwPosInterpolated_args.arg_Nz = Nz
	

	args := dwPosInterpolated_args.argptr[:]
	cu.LaunchKernel(dwPosInterpolated_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("dwPosInterpolated")
	}
}

// maps compute capability on PTX code for dwPosInterpolated kernel.
var dwPosInterpolated_map = map[int]string{ 0: "" ,
30: dwPosInterpolated_ptx_30 ,
35: dwPosInterpolated_ptx_35 ,
37: dwPosInterpolated_ptx_37 ,
50: dwPosInterpolated_ptx_50 ,
52: dwPosInterpolated_ptx_52 ,
53: dwPosInterpolated_ptx_53 ,
60: dwPosInterpolated_ptx_60 ,
61: dwPosInterpolated_ptx_61 ,
70: dwPosInterpolated_ptx_70 ,
75: dwPosInterpolated_ptx_75  }

// dwPosInterpolated PTX code for various compute capabilities.
const(
  dwPosInterpolated_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.f32 	%f3, [%rd9+4];
	ld.global.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
   dwPosInterpolated_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	dwPosInterpolated

.visible .entry dwPosInterpolated(
	.param .u64 dwPosInterpolated_param_0,
	.param .u64 dwPosInterpolated_param_1,
	.param .u64 dwPosInterpolated_param_2,
	.param .u32 dwPosInterpolated_param_3,
	.param .u32 dwPosInterpolated_param_4,
	.param .u32 dwPosInterpolated_param_5
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<19>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd1, [dwPosInterpolated_param_0];
	ld.param.u64 	%rd2, [dwPosInterpolated_param_1];
	ld.param.u64 	%rd3, [dwPosInterpolated_param_2];
	ld.param.u32 	%r3, [dwPosInterpolated_param_3];
	ld.param.u32 	%r4, [dwPosInterpolated_param_4];
	ld.param.u32 	%r5, [dwPosInterpolated_param_5];
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r6, %r7, %r8;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	setp.gt.s32	%p1, %r9, 1;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r2, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd2;
	mad.lo.s32 	%r16, %r2, %r4, %r1;
	mul.wide.s32 	%rd6, %r16, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	cvt.f64.f32	%fd1, %f1;
	add.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvt.rzi.s32.f64	%r17, %fd2;
	mad.lo.s32 	%r18, %r16, %r3, %r17;
	cvt.rn.f32.s32	%f2, %r17;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd4, %rd8;
	ld.global.nc.f32 	%f3, [%rd9+4];
	ld.global.nc.f32 	%f4, [%rd9];
	sub.f32 	%f5, %f3, %f4;
	div.rn.f32 	%f6, %f4, %f5;
	sub.f32 	%f7, %f2, %f6;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd6;
	st.global.f32 	[%rd11], %f7;

BB0_2:
	ret;
}


`
 )
