package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for setrxy kernel
var setrxy_code cu.Function

// Stores the arguments for setrxy kernel invocation
type setrxy_args_t struct{
	 arg_s unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 argptr [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for setrxy kernel invocation
var setrxy_args setrxy_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 setrxy_args.argptr[0] = unsafe.Pointer(&setrxy_args.arg_s)
	 setrxy_args.argptr[1] = unsafe.Pointer(&setrxy_args.arg_mx)
	 setrxy_args.argptr[2] = unsafe.Pointer(&setrxy_args.arg_my)
	 setrxy_args.argptr[3] = unsafe.Pointer(&setrxy_args.arg_mz)
	 setrxy_args.argptr[4] = unsafe.Pointer(&setrxy_args.arg_Nx)
	 setrxy_args.argptr[5] = unsafe.Pointer(&setrxy_args.arg_Ny)
	 setrxy_args.argptr[6] = unsafe.Pointer(&setrxy_args.arg_Nz)
	 }

// Wrapper for setrxy CUDA kernel, asynchronous.
func k_setrxy_async ( s unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Nx int, Ny int, Nz int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("setrxy")
	}

	setrxy_args.Lock()
	defer setrxy_args.Unlock()

	if setrxy_code == 0{
		setrxy_code = fatbinLoad(setrxy_map, "setrxy")
	}

	 setrxy_args.arg_s = s
	 setrxy_args.arg_mx = mx
	 setrxy_args.arg_my = my
	 setrxy_args.arg_mz = mz
	 setrxy_args.arg_Nx = Nx
	 setrxy_args.arg_Ny = Ny
	 setrxy_args.arg_Nz = Nz
	

	args := setrxy_args.argptr[:]
	cu.LaunchKernel(setrxy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("setrxy")
	}
}

// maps compute capability on PTX code for setrxy kernel.
var setrxy_map = map[int]string{ 0: "" ,
30: setrxy_ptx_30 ,
35: setrxy_ptx_35 ,
37: setrxy_ptx_37 ,
50: setrxy_ptx_50 ,
52: setrxy_ptx_52 ,
53: setrxy_ptx_53 ,
60: setrxy_ptx_60 ,
61: setrxy_ptx_61 ,
70: setrxy_ptx_70 ,
75: setrxy_ptx_75  }

// setrxy PTX code for various compute capabilities.
const(
  setrxy_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
   setrxy_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	setrxy

.visible .entry setrxy(
	.param .u64 setrxy_param_0,
	.param .u64 setrxy_param_1,
	.param .u64 setrxy_param_2,
	.param .u64 setrxy_param_3,
	.param .u32 setrxy_param_4,
	.param .u32 setrxy_param_5,
	.param .u32 setrxy_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [setrxy_param_0];
	ld.param.u64 	%rd2, [setrxy_param_1];
	ld.param.u64 	%rd3, [setrxy_param_2];
	ld.param.u32 	%r4, [setrxy_param_4];
	ld.param.u32 	%r5, [setrxy_param_5];
	ld.param.u32 	%r6, [setrxy_param_6];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd5, %r17, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f2, [%rd8];
	mul.f32 	%f3, %f2, %f2;
	fma.rn.f32 	%f4, %f1, %f1, %f3;
	sqrt.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f5;

BB0_2:
	ret;
}


`
 )
