package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for subdiv kernel
var subdiv_code cu.Function

// Stores the arguments for subdiv kernel invocation
type subdiv_args_t struct{
	 arg_sx unsafe.Pointer
	 arg_sy unsafe.Pointer
	 arg_sz unsafe.Pointer
	 arg_ax unsafe.Pointer
	 arg_ay unsafe.Pointer
	 arg_az unsafe.Pointer
	 arg_bx unsafe.Pointer
	 arg_by unsafe.Pointer
	 arg_bz unsafe.Pointer
	 arg_dt float32
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 argptr [13]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for subdiv kernel invocation
var subdiv_args subdiv_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 subdiv_args.argptr[0] = unsafe.Pointer(&subdiv_args.arg_sx)
	 subdiv_args.argptr[1] = unsafe.Pointer(&subdiv_args.arg_sy)
	 subdiv_args.argptr[2] = unsafe.Pointer(&subdiv_args.arg_sz)
	 subdiv_args.argptr[3] = unsafe.Pointer(&subdiv_args.arg_ax)
	 subdiv_args.argptr[4] = unsafe.Pointer(&subdiv_args.arg_ay)
	 subdiv_args.argptr[5] = unsafe.Pointer(&subdiv_args.arg_az)
	 subdiv_args.argptr[6] = unsafe.Pointer(&subdiv_args.arg_bx)
	 subdiv_args.argptr[7] = unsafe.Pointer(&subdiv_args.arg_by)
	 subdiv_args.argptr[8] = unsafe.Pointer(&subdiv_args.arg_bz)
	 subdiv_args.argptr[9] = unsafe.Pointer(&subdiv_args.arg_dt)
	 subdiv_args.argptr[10] = unsafe.Pointer(&subdiv_args.arg_Nx)
	 subdiv_args.argptr[11] = unsafe.Pointer(&subdiv_args.arg_Ny)
	 subdiv_args.argptr[12] = unsafe.Pointer(&subdiv_args.arg_Nz)
	 }

// Wrapper for subdiv CUDA kernel, asynchronous.
func k_subdiv_async ( sx unsafe.Pointer, sy unsafe.Pointer, sz unsafe.Pointer, ax unsafe.Pointer, ay unsafe.Pointer, az unsafe.Pointer, bx unsafe.Pointer, by unsafe.Pointer, bz unsafe.Pointer, dt float32, Nx int, Ny int, Nz int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("subdiv")
	}

	subdiv_args.Lock()
	defer subdiv_args.Unlock()

	if subdiv_code == 0{
		subdiv_code = fatbinLoad(subdiv_map, "subdiv")
	}

	 subdiv_args.arg_sx = sx
	 subdiv_args.arg_sy = sy
	 subdiv_args.arg_sz = sz
	 subdiv_args.arg_ax = ax
	 subdiv_args.arg_ay = ay
	 subdiv_args.arg_az = az
	 subdiv_args.arg_bx = bx
	 subdiv_args.arg_by = by
	 subdiv_args.arg_bz = bz
	 subdiv_args.arg_dt = dt
	 subdiv_args.arg_Nx = Nx
	 subdiv_args.arg_Ny = Ny
	 subdiv_args.arg_Nz = Nz
	

	args := subdiv_args.argptr[:]
	cu.LaunchKernel(subdiv_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("subdiv")
	}
}

// maps compute capability on PTX code for subdiv kernel.
var subdiv_map = map[int]string{ 0: "" ,
30: subdiv_ptx_30 ,
35: subdiv_ptx_35 ,
37: subdiv_ptx_37 ,
50: subdiv_ptx_50 ,
52: subdiv_ptx_52 ,
53: subdiv_ptx_53 ,
60: subdiv_ptx_60 ,
61: subdiv_ptx_61 ,
70: subdiv_ptx_70 ,
75: subdiv_ptx_75  }

// subdiv PTX code for various compute capabilities.
const(
  subdiv_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.f32 	%f2, [%rd14];
	ld.global.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.f32 	%f6, [%rd20];
	ld.global.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.f32 	%f10, [%rd26];
	ld.global.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
   subdiv_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	subdiv

.visible .entry subdiv(
	.param .u64 subdiv_param_0,
	.param .u64 subdiv_param_1,
	.param .u64 subdiv_param_2,
	.param .u64 subdiv_param_3,
	.param .u64 subdiv_param_4,
	.param .u64 subdiv_param_5,
	.param .u64 subdiv_param_6,
	.param .u64 subdiv_param_7,
	.param .u64 subdiv_param_8,
	.param .f32 subdiv_param_9,
	.param .u32 subdiv_param_10,
	.param .u32 subdiv_param_11,
	.param .u32 subdiv_param_12
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [subdiv_param_0];
	ld.param.u64 	%rd2, [subdiv_param_1];
	ld.param.u64 	%rd3, [subdiv_param_2];
	ld.param.u64 	%rd4, [subdiv_param_3];
	ld.param.u64 	%rd5, [subdiv_param_4];
	ld.param.u64 	%rd6, [subdiv_param_5];
	ld.param.u64 	%rd7, [subdiv_param_6];
	ld.param.u64 	%rd8, [subdiv_param_7];
	ld.param.u64 	%rd9, [subdiv_param_8];
	ld.param.f32 	%f1, [subdiv_param_9];
	ld.param.u32 	%r4, [subdiv_param_10];
	ld.param.u32 	%r5, [subdiv_param_11];
	ld.param.u32 	%r6, [subdiv_param_12];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd11, %r17, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.nc.f32 	%f2, [%rd14];
	ld.global.nc.f32 	%f3, [%rd12];
	sub.f32 	%f4, %f3, %f2;
	div.rn.f32 	%f5, %f4, %f1;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f5;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	ld.global.nc.f32 	%f6, [%rd20];
	ld.global.nc.f32 	%f7, [%rd18];
	sub.f32 	%f8, %f7, %f6;
	div.rn.f32 	%f9, %f8, %f1;
	cvta.to.global.u64 	%rd21, %rd2;
	add.s64 	%rd22, %rd21, %rd11;
	st.global.f32 	[%rd22], %f9;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd11;
	ld.global.nc.f32 	%f10, [%rd26];
	ld.global.nc.f32 	%f11, [%rd24];
	sub.f32 	%f12, %f11, %f10;
	div.rn.f32 	%f13, %f12, %f1;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f13;

BB0_2:
	ret;
}


`
 )
